const curiosidades = {
  1: "Colocar vinagre na panela evita que ela escureça ao cozinhar ovos dentro dela.",
  2: "O vinagre ajuda a coagular a clara se o ovo rachar durante o cozimento.",
  3: "Adicionar sal na água facilita descascar o ovo.",
  4: "Ovos mais velhos descascam mais facilmente que ovos frescos.",
  5: "O tempo de cozimento altera a textura da gema.",
  6: "Mergulhar o ovo em água gelada para o cozimento imediatamente.",
  7: "Cozinhar demais deixa a gema esverdeada (reação com enxofre).",
  8: "Ovos cozidos duram até 7 dias na geladeira.",
  9: "Ovo meio mole = cerca de 6 minutos de cozimento.",
  10: "Ovo totalmente duro = cerca de 10 minutos.",
  11: "Altitudes elevadas exigem mais tempo para cozinhar ovos.",
  12: "Furar a parte larga evita rachaduras.",
  13: "Adicionar bicarbonato facilita a remoção da casca.",
  14: "A clara cozinha antes da gema.",
  15: "A membrana sob a casca ajuda a proteger o ovo ao cozinhar.",
  16: "Evite cozinhar com fervura muito forte.",
  17: "Você pode fazer ovos cozidos no forno a 160 °C por 30 min.",
  18: "Ovo cozido gira mais rápido que um cru.",
  19: "Mergulhar o ovo em água com gelo ajuda a descascar melhor.",
  20: "Ovo fresco afunda na água. Velho boia.",
  21: "Evite cozinhar ovos que tenham rachaduras.",
  22: "Pingar limão ou vinagre evita vazamentos.",
  23: "Cozinhe ovos com casca colorida para eventos (com corante natural).",
  24: "Marinar ovos cozidos cria os famosos 'eggs ramen'.",
  25: "O aroma de enxofre vem de cozimento excessivo.",
  26: "Casca trincada pode causar perda da clara.",
  27: "Use uma colher para bater levemente antes de cozinhar para centralizar a gema.",
  28: "Para um ovo firme, evite gelo depois de cozido.",
  29: "Evite colocar muitos ovos na panela ao mesmo tempo.",
  30: "O centro ideal da gema é ligeiramente cremoso.",
  31: "Para ovos moles, comece a contar o tempo após a fervura.",
  32: "Você pode cozinhar ovos no microondas com cuidado.",
  33: "Cascas podem ser trituradas e usadas como adubo.",
  34: "Evite reutilizar água do cozimento por causa de resíduos de proteína.",
  35: "Descascar com o ovo ainda morno é mais fácil.",
  36: "Cozinhar ovos em panela de inox preserva melhor o sabor.",
  37: "Cozinhar com água filtrada evita manchas na casca.",
  38: "Ovos de casca marrom e branca cozinham igual, muda só a galinha.",
  39: "A temperatura ideal da geladeira mantém o ovo firme para cozinhar.",
  40: "Panelas de alumínio podem escurecer com o cozimento.",
  41: "A casca do ovo é porosa, cuidado com odores na geladeira.",
  42: "Evite cozinhar ovos diretamente do freezer.",
  43: "Cozinhe ovos por lote e guarde com data para não se perder.",
  44: "Panelas com tampa conservam melhor o calor e o tempo de cozimento.",
  45: "Água com corante natural (beterraba, cúrcuma) colore os ovos.",
  46: "Ferver com uma colher de chá de óleo ajuda a não grudar.",
  47: "Evite chocar ovos quentes direto em superfícies frias para não racharem.",
  48: "Ovos pequenos cozinham mais rápido que grandes.",
  49: "Use timer! O tempo muda completamente o resultado.",
  50: "Você pode assar ovos com casca em forma de cupcake no forno."
};

export default curiosidades;
